[package]
name = "aggregator_bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aggregator = { path = "/home/aaron/workspaces/rust/aggregator", version = "0.1.0" }