# General tools
alias bashrc="source ~/.bashrc"

git_ssh_clone () {
  git clone ssh://git@github.com/$1/$2.git
}
git_clone() {
  git clone https://github.com/$1/$2.git
}

# BAZEL
export PATH="$PATH:$HOME/bin"

# ROS
alias r1="source /opt/ros/melodic/setup.bash"
alias r2c="source /opt/ros/crystal/setup.bash"
alias r2d="source /opt/ros/dashing/setup.bash"
alias r2e="source /opt/ros/eloquent/setup.bash"

alias rmw_cyclone="export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp"
alias rmw_frtps="export RMW_IMPLEMENTATION=rmw_fastrtps_cpp"

export ROS_DOMAIN_ID=128

# Gazebo
alias killgazebo="pkill -9 gzserver && pkill -9 gzclient && pkill -9 gazebo"

# CUDA
export PATH=/usr/local/cuda/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}

# rust
export PATH="$PATH:$HOME/.cargo/bin"

